### ISSUE TITLE
Can not import in allzparkconfig.py

### ISSUE THREAD

**Issue by ClementHector** [mottosso/allzpark#100]
First thanks for this app, I put it in the studio but I have a little problem.
I launch allzpark with the argument --config-file path/to/allzparkconfig.py. In the allzparkconfig.py file, I want to import a module which is added to PYTHONPATH before launching.
But the import does not pass, and  i don't have any error.
Do you know why?

Thank in advance.

**Comment by mottosso** [comment]
Hi @ClementHector, could you show me how to reproduce the problem on my machine? It sounds like something like this.

**allzparkconfig.py**

```py
import os
os.environ["PYTHONPATH"] = "c:/my/dir"
```

And that you then launch an application, say `Maya 2019` and expect Maya to have access to this environment variable, is that right?

**Comment by ClementHector** [comment]
Sorry for the misunderstanding.

If i put this code in a config file, call by the argurment:

**allzparkconfig.py**
```
import sys
sys.path.append(r"/path/to/api") # where the shotgun api is.
import shotgun_api3 # don't import of shotgun_api3 or other api from sys.path
print("test") # don't print "test"
```
It doesn't work, but I just saw that it works if I put the same code in the installation file allzparkconfig.py

**Comment by mottosso** [comment]
So wait, does it or doesn't it work?

> If i put this code in a config file

Where do you put this file? E.g. `c:\users\marcus\allzparkconfig.py`?

> if I put the same code in the installation file allzparkconfig.py

Which installation file? How do you install?

If you can help me reproduce the problem I might be able to figure this one out. Could you show me the steps, on a new machine, how to spot the problem?

**Comment by ClementHector** [comment]
> Where do you put this file?

Where you want, for me: 
`R:/PIPELINE/__PACKAGES__/allzparkconfig.py`
So i start allzpark with the command: 
`allzpark --config-file R:/PIPELINE/__PACKAGES__/allzparkconfig.py`


> Which installation file? How do you install?

 I install allzpark with the command:
`py -3.7 pip install allzpark`
and after i change the file:
`C:\Python37\Lib\site-packages\allzpark\allzparkconfig.py`
Finaly i start allzpark with no config file, so the command is:
`allzpark`

**Comment by ClementHector** [comment]
Excuse me for the bad problem, it came from incompatibile library, after an update everything works good.

**Comment by mottosso** [comment]
No problem @ClementHector, thanks for the update and happy to hear it works!
