### ISSUE TITLE
Missing collect .svg icons in setup.py

### ISSUE THREAD

**Issue by loonghao** [mottosso/allzpark#114]
Hi,

when I via command line `rez env pipz -- install allzpark` to install, I found that some SVG icons are missing in the profile widget.
 
![image](https://user-images.githubusercontent.com/13111745/96820542-c6ce0480-1458-11eb-8863-fb9fd7e38afa.png)

**Comment by mottosso** [comment]
Thanks for reporting this @loonghao, looks like we've missed to include a few new assets with the latest merge, #110 

Until that is fixed, or if you would like to have a go at making a PR to fix it, try using the previous version from PyPI.

@davidlatwe We should be able to resolve this by including additional files the same way that other icons are included. That `setup.py` file can be strict about which files come along.
