### ISSUE TITLE
graph update error

### ISSUE THREAD

**Issue by chowooseoung** [mottosso/allzpark#136]
os : windnow10 
If you press the graph update button, an error occurs. I register the issue because I don't know if it's my mistake or an error.

![error](https://user-images.githubusercontent.com/49386821/103091440-839a3880-4637-11eb-9067-1292951273f1.PNG)
![error2](https://user-images.githubusercontent.com/49386821/103091443-872dbf80-4637-11eb-93b3-353cc54d8990.PNG)

**Comment by davidlatwe** [comment]
Hi @chowooseoung , that probably because of the fresh installed graphviz without proper config.

Try `dot -c` in terminal, see [here](https://stackoverflow.com/a/62549025/14054728).

**Comment by chowooseoung** [comment]
thank you ! 
It works well.
