### ISSUE TITLE
Allzpark seems to be only loading/displaying one profile

### ISSUE THREAD

**Issue by gwhite-fr** [mottosso/allzpark#142]
Just getting into Rez and Allzpark -- I've installed and followed the quickstart but I'm running into an issue in the demo where I only see the Alita profile in the dropdown UI. I figured I'd forge ahead and see if I ran into the same issue when it came time to create my own profiles for my projects and I'm experiencing the same issue at that point. I'm attaching two screenshots -- one for the demo issue and one showing the same with two test profiles, kingkong & gregtest. Any ideas?
![allzpark-demo-issue](https://user-images.githubusercontent.com/90282974/133361839-57e771d4-e570-46a6-81a0-916c6ae031ad.PNG)
![allzpark-profile-issue](https://user-images.githubusercontent.com/90282974/133361846-1107f866-be5f-4d20-b3a2-e5d2ea30851e.PNG)

**Comment by davidlatwe** [comment]
Hi, maybe try toggling the filter icon on the left side of the profile list ?

**Comment by gwhite-fr** [comment]
Well I feel dumb -- I could have sworn I had clicked just about every button by now. Thanks David - the profile list under the profile pane is now showing what I would expect but the icon at the top still only shows the current profile, is that just a change in the UI overall compared to the Quickstart look?  Just want to make sure what I'm getting is correct -- I can still switch profiles now by right-clicking and Activating. Either way - thanks for the quick response
![allzpark-profiles](https://user-images.githubusercontent.com/90282974/133368400-5fa9b841-e63d-41e0-90b1-16dee755445a.PNG)

**Comment by davidlatwe** [comment]
Ouch, the GIFs in Quickstart guide indeed are outdated. 🤕 

It's from this release 👉🏼 https://github.com/mottosso/allzpark/releases/tag/1.3.0
And yes, the top icon only indicating current profile now.

**Comment by mottosso** [comment]
Glad to see you got this sorted @gwhite-fr! If either you or David is able to make a quick 3-5 second gif (or mp4) using the Profile panel, I'd be happy to update the README and Quickstart with this for future users.

**Comment by gwhite-fr** [comment]
Sure - here's a quick go at that -- thanks for the help, looking forward to working with Allzpark more!
![Allzpark-ProfileFilters](https://user-images.githubusercontent.com/90282974/133529630-ed1522de-ff65-486b-b175-d8d0e3521c06.gif)

**Comment by davidlatwe** [comment]
That's AWESOME !

**Comment by mottosso** [comment]
README updated, thanks @gwhite-fr!
