### ISSUE TITLE
installing into venv throws rez error for "--quickstart" option

### ISSUE THREAD

**Issue by frueter** [mottosso/allzpark#145]
I just tried the fllowing to install allzpark into a virtual environment to avoid permission errors on OSX Ventura:

`python3 -m venv allzpark-venv`
`source ./allzpark-venv/bin/activate`
`(allzpark-venv) frank@wormwood venvs % pip install allzpark --upgrade`
Then I tried the next step as per the quickstart guide:
`(allzpark-venv) frank@wormwood venvs % rez bind --quickstart`
but got produced this error:
`### rez - The option --quickstart is not yet implemented.
### rez - Usage: rez [-a] [-al word | longword] [-arch arch] [-c creator] [-d name[=value]] [-i path] [-isysroot path] [-F framework] [-m] [-noResolve [output | include]] [-o file] [-ov] [-p] [-rd] [-ro] [-s path] [-sc script] [-t type] [-u name] [-useDF] [file...].`

This was not the case when I tried to install it outside the venv (though I got stuck with permission error and `python` not being found (as per my other issue).

**Comment by frueter** [comment]
I uninstalled and reinstalled wiht the --upgrade option (which is missing from the venv instructions in the quickstart guide) and that seemed to make that part work.

**Comment by mottosso** [comment]
Thanks for flagging this @frueter

> (which is missing from the venv instructions in the quickstart guide)

Our quickstart is also in this repo, and a pull request to touch things up is most welcome.

- https://github.com/mottosso/allzpark/tree/master/docs/pages

Changes to here are automatically reflected in the live website documentation.

**Comment by frueter** [comment]
Thanks Marcus,

I have proposed changes and created a pull request. I hope I have done this
right, first time :)
