### ISSUE TITLE
ALLZPARK_CONFIG_FILE env variable not beeing read on windows

### ISSUE THREAD

**Issue by tlhommeperso** [mottosso/allzpark#148]
Hello guys, 
I just installed allzpark clean and fresh from scratch and setup the env variable.
ALLZPARK_CONFIG_FILE to point to a glabal studio locaiton but funny enough its never beeing read when i launch 
`allzpark `as is or with 
`allzpark --config-file "MY PATH TO CONFIG"`

any clue why ?

**Comment by mottosso** [comment]
Heya, 

The answer will be somewhere in here.

- [`--config](https://github.com/mottosso/allzpark/blob/master/allzpark/cli.py#L364)
- Which is passed to [initialize here](https://github.com/mottosso/allzpark/blob/master/allzpark/cli.py#L403)
- And loaded [here](https://github.com/mottosso/allzpark/blob/master/allzpark/cli.py#L208)

I'd put some print statements here to see what comes up, or look closer at what could have happened prior to the load.

**Comment by tlhommeperso** [comment]
Manage to find that i had some errors in my own config :) cheers for your more than fast reaction really appreciate it :)
