### ISSUE TITLE
Option to "forget" user environment

### ISSUE THREAD

**Issue by mottosso** [mottosso/allzpark#54]
Sometimes, the user may launch an application and spot a really old environment having been set. Where did this come from? He looks at his local system environment and finds nothing. Later, he discovers that a few months ago, the value is coming from his now outdated Allzpark user environment.

### Implementation

Add an option to forget it in the Preferences tab.

**Comment by davidlatwe** [comment]
> Add an option to forget it in the Preferences tab.

Or adding an indicator like what #125 did, to indicate user environment has input ?

**Comment by mottosso** [comment]
Sure, that might work. Let's reopen this if the problem resurfaces.
