### ISSUE TITLE
User Themes

### ISSUE THREAD

**Issue by mottosso** [mottosso/allzpark#82]
### Goal

Facilitate creation, storing and selecting of user profiles.

### Motivation

Currently, you can author your own css (#13), but it's a one-off. If you wanted another "theme" you'd have to delete your old (or manually save it somewhere else). And if you wanted to download a theme someone else has made, same story.

### Implementation

Add a `css_path` variable to allzparkconfig.py whereby users can provide their own absolute paths to folders of CSS files. The name of each file would then appear in a drop-down menu of the CSS tab for users to choose between.

**Comment by davidlatwe** [comment]
Functionally, the goal of this issue has been implemented in #111. Although the implementation is a bit different, still mark this as resolved :D
