### ISSUE TITLE
Bad ordering of PATH-like variables in Environment Tab

### ISSUE THREAD

**Issue by mottosso** [mottosso/allzpark#91]
Needs some tuning, akin to how project and package versions are sorted.

![image](https://user-images.githubusercontent.com/2152766/62598310-e1ae6a80-b8e0-11e9-8485-257a282d635f.png)

**Comment by davidlatwe** [comment]
It seems that, remove the `str` convesion at this line fixed the issue 👇🏼 

https://github.com/mottosso/allzpark/blob/1d7f3dbd1d742dbd792f3ee642ac726e1cbca0a4/allzpark/vendor/qjsonmodel.py#L116

Were there any reason to do so ? 🤔

**Comment by mottosso** [comment]
Hm, well qjsonmodel is not my project (well, kind of). We could modify it here, but probably best to try and tackle it from within Allzpark, or make the change upstream in qjsonmodel, or - worst case - make a local change here.
