### ISSUE TITLE
missing package in profile and profile swap feels strange

### ISSUE THREAD

**Issue by TravisEvashkevich** [mottosso/allzpark#93]
![image](https://user-images.githubusercontent.com/7120085/62606533-5c34b580-b8f4-11e9-8e70-1cd6f102a1cb.png)
Upgraded to the newest release and was greeted by this (can't seem to get passed it to see other apps etc.)

Also, swapping profiles from the dropdown feels a bit janky
![profileswapping](https://user-images.githubusercontent.com/7120085/62606863-fd237080-b8f4-11e9-9bda-21dc006163dc.gif)
I would assume that clicking the dropdown and then a profile name that is not my current would instantly swap to that one without requiring pressing the picture or pressing enter on my keyboard.

**Comment by mottosso** [comment]
Thanks for reporting this @TravisEvashkevich, investigating.

**Comment by mottosso** [comment]
Fixed in 1.2.183.

> I would assume that clicking the dropdown and then a profile name that is not my current would instantly swap to that one without requiring pressing the picture or pressing enter on my keyboard.

About this, yes you are right. It's part of an ongoing bug-hunt, see https://github.com/mottosso/allzpark/issues/86. A PR would be most welcome. One that's fixed, we'll be able to listen in on when the popup closes and automatically switch projects.
