### ISSUE TITLE
Change Application Version

### ISSUE THREAD

**Issue by mottosso** [mottosso/allzpark#96]
### Goal

Facilitate having multiple versions of an applications in a given profile.

### Motivation

Currently, you can have more than one application [like this](https://allzpark.com/gui/#multiple-application-versions). But that takes up a lot of space.

### Implementation

Make the application version editable.

![image](https://user-images.githubusercontent.com/2152766/62832568-91107780-bc28-11e9-8194-712fe3858285.png)

**Comment by davidlatwe** [comment]
Implemented in #129 :)
