### ISSUE TITLE
[new install] PySide2; python_version > "3" (from allzpark)

### ISSUE THREAD

**Issue by dingdong88** [mottosso/allzpark#98]
new machine and just installed python3 then run 
python -m pip install allzpark --upgrade

Collecting PySide2; python_version > "3" (from allzpark)
  ERROR: Could not find a version that satisfies the requirement PySide2; python_version > "3" (from allzpark) (from versions: none)
ERROR: No matching distribution found for PySide2; python_version > "3" (from allzpark)

**Comment by dingdong88** [comment]
sorry was using a non-release version of python.

**Comment by mottosso** [comment]
No problem @dingdong88. You should be good to go using `pip install allzpark --no-deps`, and provide your own version of PySide, PySide2, PyQt4 or PyQt5; Allzpark will work with either of those.
